title: Simbiose Knowledge Pool
logo: "/assets/images/logo.png"
baseurl: "https://s1mbi0se.github.io/knowledge-pool/"

# Build settings
remote_theme: pmarsceill/just-the-docs

# Define Jekyll collections
collections:
  topics:
    output: true
  teams:
    output: true

#just_the_docs:
#  # Define which collections are used in just-the-docs
#  collections:
#    # Reference the "docs" collection
#    posts:
#      # Give the collection a name
#      name: Posts
#      # Exclude the collection from the navigation
#      # Supports true or false (default)
#      nav_exclude: true
#      # Exclude the collection from the search
#      # Supports true or false (default)
#      search_exclude: false